#!/bin/bash

NAME="analyzer"
VERSION="1.0"
SCALA_VERSION="2.11"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JAR="$DIR/target/scala-$SCALA_VERSION/$NAME-assembly-$VERSION.jar"

OWNER=$1
REPOSITORY=$2
GIT_LOCATION="$( cd "$3" && pwd )"
TIMESTAMP=$4

if ! [ -f "$JAR" ]; then
  echo "JAR file does not exist." >&2
  echo "Make sure you run \`sbt assembly\` to build the JAR executable." >&2
  exit 1
fi

if [ "$#" -ne 3 ] && [ "$#" -ne 4 ]; then
  echo "Wrong number of arguments, expected 3 or 4 arguments." >&2
  echo "Usage: $0 owner_name repository_name git_location [timestamp]" >&2
  exit 1
fi

case "$OWNER$REPOSITORY$GIT_LOCATION" in
  *\ * )
  echo "Whitespace is not supported." >&2
  exit 1
  ;;
esac

if ! [ -d "$GIT_LOCATION" ]; then
  echo "Git repository does not exist." >&2
  exit 1
fi

JAVA_OPTS="-Dfile.encoding=UTF8 -Dgithub.owner=$OWNER -Dgithub.repository=$REPOSITORY -Djgit.directory=$GIT_LOCATION -Dupdate.timestamp=$TIMESTAMP"
java $JAVA_OPTS -jar $JAR
